---
build_from:
  aarch64: ghcr.io/hassio-addons/base:14.1.0
  amd64: ghcr.io/hassio-addons/base:14.1.0
  armhf: ghcr.io/hassio-addons/base:14.1.0
  armv7: ghcr.io/hassio-addons/base:14.1.0
  i386: ghcr.io/hassio-addons/base:14.1.0
codenotary:
  base_image: slamdf150xc@gmail.com
  signer: slamdf150xc@gmail.com
