---
name: GenMon
version: 0.1.01
slug: genmon
description: GenMon add-on for Home Assistant
url: https://github.com/slamdf150xc/Genmon-addon
codenotary: slamdf150xc@gmail.com
init: false
hassio_api: true
hassio_role: default
map:
  - share:rw
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  sitename: "SiteName"
  serial_tcp_ip_address: 10.10.10.35
  serial_tcp_port: 6638
schema:
  sitename: str?
  serial_tcp_ip_address: str?
  serial_tcp_port: port?
  generator_size: int?
  fuel_type: list(Natural Gas|Propane|Diesel|Gasoline)?
  enable_mqtt: bool?
  mqtt_ip_address: str?
  mqtt_username: str?
  mqtt_password: password?
  mqtt_port: port?
ingress: true
ingress_port: 8000
panel_icon: mdi:engine-outline
