---
name: GenMon
version: dev
slug: genmon
description: GenMon add-on for Home Assistant
url: https://github.com/slamdf150xc/Genmon-addon
codenotary: slamdf150xc@gmail.com
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
ingress: true
ingress_port: 8000
panel_icon: mdi:engine-outline